### PR TITLE
Linear stepping, provides more torque, and doesn't stop/deccelorate between shots. 

### PR DESCRIPTION
**Pull request by MatthewBregg**
No more RoF support, and always fires at least one dart per trigger pull to make semi auto firing when in full auto easier.

A bit messy, need to remove some extraneous constants from the linear stepper code and I believe line 367 is a dead path, but working with my FDL.

### CODE REVIEW

**Comment by MatthewBregg** [comment]
Refactored the initial merged code again.
Mainly cleaned up fireBrushlessLoop.

**Comment by MatthewBregg** [comment]
Also at this point I should be done with cleaning up the code.
Sorry if you were already reviewing this PR and I pulled the rug out from under you.

**Comment by projectfdl** [comment]
Looks great, if you could do me a favor and commit this to a branch instead of master? I'd like to get this into the repo then piece it into master once I can sit down with it.

**Comment by MatthewBregg** [comment]
Sure, I'm fairly certain you have to create the branch though, as I have no write access to this repo.

If you make a branch in this project, like linear stepping, then it should be easy to change the target of this pr.

**Comment by MatthewBregg** [comment]
Changed target to merge into linear stepping branch

**Pull request merged**
